### ISSUE TITLE
Suggestion - simple way to let TI charging circuit power and charge calculator

### ISSUE THREAD

**Issue by magore** [tomcircuit/TI59_battery#1]
I love your project. This is just a suggestion and not a bug report.

I have a number of TI-59 calculators and your project got me thinking.
I wondered if there was a way to use the existing TI charging circuit (basically a bridge rectifier feed from an externally AC transformer - that was current limited by design) to both charge and power the calculator when plugged in?

First requirement is filter and stabilize the power from the spring contacts. Let that filtered voltage feed a Lipo charging circuit in the battery pack that provides both load/out and charging on its output. When the charger is plugged in the calculator runs from the charger and the LIPO can also charge if needed. When not plugged in calculator runs only from the LIPO. The bridge rectifier prevents back flow from the charger.

Testing I have tried - I have connected a simple LIPO charging circuit to the spring contacts filtered with just a 1000uF cap. With the calculator OFF the spring contacts measure 4.3V and can fully charge the LIPO. However with the calculator ON the voltage drops to 4.0V. So basically the LIPO will not get a full charge unless the calculator is off.

**Comment by tomcircuit** [comment]
Thanks for writing, and I’m glad you found my project interesting! I has some thoughts about trying to do what you propose, but didn’t like the complexity (i.e. I was lazy!)

I seem to recall reading that the TI AC charger current limiting was set so that it would just manage to trickle charge the NiCd cells while the calc was operating. So your measurement of 4V with calc on (and no card reader motor I presume) sounds about right.  I think the most straightforward solution would be to use a boost-type charging circuit, such as used with solar cells. You would also likely need to set the charging current much lower (10’s of mA) to avoid “brownout”. Please keep me posted as to your progress!!

**Comment by magore** [comment]
Thanks for the feedback
